name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: 82.180.142.181
      SSH_USER: u264513720
      SSH_PORT: 65002
      DEPLOY_PATH: /home/u264513720/domains/ornasphere.com/public_html

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node Modules
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "echo SSH Connected"

      - name: Create Deploy Directory
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST \
          "mkdir -p '$DEPLOY_PATH'"

      - name: Upload Files
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='storage' \
            --exclude='.env' \
            -e "ssh -p $SSH_PORT" \
            ./ \
            $SSH_USER@$SSH_HOST:$DEPLOY_PATH

      - name: Laravel Deployment
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST << EOF

          cd $DEPLOY_PATH

          composer install \
            --no-dev \
            --optimize-autoloader \
            --no-interaction

          php artisan optimize:clear

          php artisan migrate --force

          php artisan storage:link || true

          php artisan config:cache

          php artisan route:cache

          php artisan view:cache

          chmod -R ug+rw storage bootstrap/cache

          EOF